### ISSUE TITLE
new report - connection type

### ISSUE THREAD

**Issue by x4080** [majorsilence/My-FyiReporting#127]
Hello, Im new user in my-fyireporting, first, I'm using nuget package manager : my-fyireporting x.86 and cannot resolve the ViewerToolstrip, so I download version 4.9 from http://build01.majorsilence.com/job/Majorsilence%20Reporting%20-%20Build/47/
(and the viewertoolstrip is now working)

while im there, there is a file name "4.9-majorsilence-reporting-build-dot-net-4-AnyCPU.zip", when I extracted it, theres' runtime of RdlDesigner, but with this version, all connection from rdlengineconfig.xml is not appear (like sqlce, oracle etc)

the options just filedirectory, shared data source,odbc, oledb, sql,text,weblog,webservice,xml

Did I do something wrong ? Or the newest one have fewer connections? But the rdlengineconfig.xml is still there

Help?

Thanks

**Comment by x4080** [comment]
It seems the problem is in the rdlengineconfig.xml because of empty spaces at the top and the bottom, after that I have another problem, I was able to connect to advantage database server (designer version 4.5) but now using the newest version (4.9) error when test connection :
An attempt was made to load a program with an incorrect format (exception from HRESULT:0x8007000b)

Is the new designer is 64 bit ? My driver is 32 bit if Im not wrong

Thanks

**Comment by majorsilence** [comment]
If you are using the nuget packages switch to the [MajorsilenceReporting](https://www.nuget.org/packages?q=majorsilencereporting) packages.  It is currently on version 4.12.  There have been many bug fixes since 4.9.  I have now unlisted My-FyiReporting nuget packages.

Make sure RdlEngineConfig.xml is copied to your programs output folder.

You can always see the latest release information at https://github.com/majorsilence/My-FyiReporting/wiki/Downloads.

**Comment by x4080** [comment]
Thanks for the tip
