### ISSUE TITLE
RdlReader too slow to render when run with Mono in OSX El Capitan. 

### ISSUE THREAD

**Issue by arisrell** [majorsilence/My-FyiReporting#140]
When running RdIReader.exe to view a report in OSX using Mono, I find that the RdlReader is taking too much time to render, over 3 minutes, to show a report with 1,500 rows. However, it only takes 3 seconds in Windows.

How can I speed up the rendering in OSX El Capitan?

**Comment by Gankov** [comment]
Please try GtkViewer for mono. https://github.com/majorsilence/My-FyiReporting/tree/master/RdlGtkViewer This normally works on Linux and Mac. We use it.
You can also try Xwt Viewer https://github.com/majorsilence/My-FyiReporting/tree/master/LibRdlCrossPlatformViewer but i personally did not test it.
Work WinForms viewer on mono seems no need because exist more native viewers, But if you want you can fix it and push patch to fix issue.

**Comment by arisrell** [comment]
Hi

Thank you so much for your response. 

I tried to use the RdlGtkViewer but don't know how to start it up to automatically open a report with the parameters.  It just shows a window where you can manually load a report.

I trried to follow the example in the Wiki but I get BadImageformat error. 

What should I do to make RdlGtkViewer to just accept rdl and parameters like RdlReader does.

I even tried to changed the output to dll.

I tried to fix the issue with RdlViewer and narrowed the slowness down to the Runpage() of a TableCell object where it tries to render each textbox.  It seems its taking a while to calculate the float location coordinates. But only in Mono for OSX. Both Windows and Ubuntu can display 1500 rows in 3 seconds.
Must be an issue with Mono for OSX.

Thanks

**Comment by arisrell** [comment]
Use Report Server instead.
